export const COMPANIES = {
  localhost: {
    id: "localhost",
    name: "localhost",
    apiUrl: "http://localhost:3001/admin/api/",
    publicApiUrl: "http://localhost:4000/admin/api/",
    socketUrl: "http://localhost:3001",
    logo: "/images/logo/emtech88.png",
    currency: "MYR",
    template: 1,
    features: {
      transaction: true,
      user: true,
      agent: true,
      agentpt: true,
      website: true,
      luckyspin: true,
      blog: true,
      mail: true,
      feedback: true,
      promocode: true,
      kiosk: true,
      bank: true,
      crypto: true,
      carousel: true,
      admin: true,
      promotion: true,
      vip: true,
      rebate: true,
      report: true,
      tools: true,
      seo: true,
      verification: true,
      paymentgateway: true,
      setting: true,
      oc7: true,
      ae96: true,
      bm8my: true,
      affiliate: true,
      gamelist: true,
    },
  },
  ae96: {
    id: "ae96",
    name: "ae96",
    apiUrl: "https://api.ae96.club/admin/api/",
    publicApiUrl: "https://api.mysteryclub88.co/admin/api/",
    socketUrl: "https://api.ae96.club",
    logo: "/images/logo/ae96.png",
    currency: "AUD",
    features: {
      transaction: true,
      user: true,
      agent: true,
      agentpt: false,
      website: true,
      luckyspin: true,
      blog: true,
      mail: true,
      feedback: true,
      promocode: true,
      kiosk: true,
      bank: true,
      crypto: false,
      carousel: true,
      admin: true,
      promotion: true,
      vip: true,
      rebate: true,
      report: true,
      tools: false,
      seo: true,
      verification: true,
      paymentgateway: true,
      setting: true,
      oc7: false,
      ae96: true,
      bm8my: false,
      affiliate: false,
      gamelist: false,
    },
  },
  demo: {
    id: "demo",
    name: "demo",
    apiUrl: "https://api.emtech88.com/admin/api/",
    publicApiUrl: "https://api.mysteryclub88.co/admin/api/",
    socketUrl: "https://api.emtech88.com",
    logo: "/images/logo/emtech88.png",
    currency: "MYR",
    features: {
      transaction: true,
      user: true,
      agent: true,
      agentpt: false,
      website: true,
      luckyspin: true,
      blog: true,
      mail: true,
      feedback: true,
      promocode: true,
      kiosk: true,
      bank: true,
      crypto: false,
      carousel: true,
      admin: true,
      promotion: true,
      vip: true,
      rebate: true,
      report: true,
      tools: false,
      seo: true,
      verification: false,
      paymentgateway: true,
      setting: true,
      oc7: false,
      ae96: false,
      bm8my: false,
      affiliate: false,
      gamelist: false,
    },
  },
  stash88: {
    id: "stash88",
    name: "stash88",
    apiUrl: "https://api.stash88.com/admin/api/",
    publicApiUrl: "https://api.mysteryclub88.co/admin/api/",
    socketUrl: "https://api.stash88.com/",
    logo: "/images/logo/stash88.png",
    currency: "MYR",
    template: 1,
    features: {
      transaction: true,
      user: true,
      agent: true,
      agentpt: true,
      website: true,
      luckyspin: true,
      blog: true,
      mail: true,
      feedback: true,
      promocode: true,
      kiosk: true,
      bank: true,
      crypto: true,
      carousel: true,
      admin: true,
      promotion: true,
      vip: true,
      rebate: true,
      report: true,
      tools: true,
      seo: true,
      verification: true,
      paymentgateway: true,
      setting: true,
      oc7: false,
      ae96: false,
      bm8my: false,
      affiliate: true,
      gamelist: false,
    },
  },
  oc7: {
    id: "oc7",
    name: "oc7",
    apiUrl: "https://api.oc7.me/admin/api/",
    publicApiUrl: "https://api.mysteryclub88.co/admin/api/",
    socketUrl: "https://api.oc7.me",
    logo: "/images/logo/oc7.png",
    currency: "MYR",
    features: {
      transaction: true,
      user: true,
      agent: true,
      agentpt: true,
      website: true,
      luckyspin: true,
      blog: true,
      mail: true,
      feedback: true,
      promocode: true,
      kiosk: true,
      bank: true,
      crypto: false,
      carousel: true,
      admin: true,
      promotion: true,
      vip: true,
      rebate: true,
      report: true,
      tools: false,
      seo: true,
      verification: true,
      paymentgateway: true,
      setting: true,
      oc7: true,
      ae96: false,
      bm8my: false,
      affiliate: false,
      gamelist: false,
    },
  },
  ezwin9: {
    id: "ezwin9",
    name: "ezwin9",
    apiUrl: "https://api.ezwin9.com/admin/api/",
    publicApiUrl: "https://api.mysteryclub88.co/admin/api/",
    socketUrl: "https://api.ezwin9.com/",
    logo: "/images/logo/ezwin9.png",
    currency: "HKD",
    template: 1,
    features: {
      transaction: true,
      user: true,
      agent: true,
      agentpt: true,
      website: true,
      luckyspin: true,
      blog: true,
      mail: true,
      feedback: true,
      promocode: true,
      kiosk: true,
      bank: true,
      crypto: true,
      carousel: true,
      admin: true,
      promotion: true,
      vip: true,
      rebate: true,
      report: true,
      tools: true,
      seo: true,
      verification: true,
      paymentgateway: true,
      setting: true,
      oc7: false,
      ae96: false,
      bm8my: false,
      gamelist: true,
    },
  },
  jinlihui: {
    id: "jinlihui",
    name: "jinlihui",
    apiUrl: "https://api.jinlihui.net/admin/api/",
    publicApiUrl: "https://api.mysteryclub88.co/admin/api/",
    socketUrl: "https://api.jinlihui.net/",
    logo: "/images/logo/jinlihui.png",
    currency: "RMB",
    features: {
      transaction: true,
      user: true,
      agent: true,
      agentpt: false,
      website: true,
      luckyspin: true,
      blog: true,
      mail: true,
      feedback: true,
      promocode: true,
      kiosk: true,
      bank: true,
      crypto: false,
      carousel: true,
      admin: true,
      promotion: true,
      vip: true,
      rebate: true,
      report: true,
      tools: false,
      seo: true,
      verification: true,
      paymentgateway: true,
      setting: true,
      oc7: false,
      ae96: false,
      bm8my: false,
      affiliate: false,
      gamelist: false,
    },
  },
  wantokplay: {
    id: "wantokplay",
    name: "wantokplay",
    apiUrl: "https://api.wantokplay.com/admin/api/",
    publicApiUrl: "https://api.mysteryclub88.co/admin/api/",
    socketUrl: "https://api.wantokplay.com/",
    logo: "/images/logo/wantokplay.png",
    currency: "PGK",
    template: 1,
    features: {
      transaction: true,
      user: true,
      agent: true,
      agentpt: true,
      website: true,
      luckyspin: true,
      blog: true,
      mail: true,
      feedback: true,
      promocode: true,
      kiosk: true,
      bank: true,
      crypto: true,
      carousel: true,
      admin: true,
      promotion: true,
      vip: true,
      rebate: true,
      report: true,
      tools: true,
      seo: true,
      verification: true,
      paymentgateway: true,
      setting: true,
      oc7: false,
      ae96: false,
      bm8my: false,
      gamelist: true,
    },
  },
  bm8my: {
    id: "bm8my",
    name: "bm8my",
    apiUrl: "https://api.egm8my.vip/admin/api/",
    publicApiUrl: "https://api.mysteryclub88.co/admin/api/",
    socketUrl: "https://api.egm8my.vip",
    logo: "/images/logo/bm8my.png",
    currency: "MYR",
    features: {
      transaction: true,
      user: true,
      agent: true,
      agentpt: true,
      website: true,
      luckyspin: true,
      blog: true,
      mail: true,
      feedback: true,
      promocode: true,
      kiosk: true,
      bank: true,
      crypto: false,
      carousel: true,
      admin: true,
      promotion: true,
      vip: true,
      rebate: true,
      report: true,
      tools: false,
      seo: true,
      verification: true,
      paymentgateway: true,
      setting: true,
      oc7: false,
      ae96: false,
      bm8my: true,
      affiliate: false,
      gamelist: false,
    },
  },
  bm8sg: {
    id: "bm8sg",
    name: "bm8sg",
    apiUrl: "https://api.egm8sg.vip/admin/api/",
    publicApiUrl: "https://api.mysteryclub88.co/admin/api/",
    socketUrl: "https://api.egm8sg.vip",
    logo: "/images/logo/bm8sg.png",
    currency: "SGD",
    features: {
      transaction: true,
      user: true,
      agent: true,
      agentpt: true,
      website: true,
      luckyspin: true,
      blog: true,
      mail: true,
      feedback: true,
      promocode: true,
      kiosk: true,
      bank: true,
      crypto: false,
      carousel: true,
      admin: true,
      promotion: true,
      vip: true,
      rebate: true,
      report: true,
      tools: false,
      seo: true,
      verification: true,
      paymentgateway: true,
      setting: true,
      oc7: false,
      ae96: false,
      bm8my: false,
      affiliate: false,
      gamelist: false,
    },
  },
};

export const getCompanyApiUrl = (companyId) => {
  if (!companyId || !COMPANIES[companyId]) {
    console.error(`Invalid company ID: ${companyId}`);
    return "";
  }
  return COMPANIES[companyId].apiUrl;
};

export const getPublicApiUrl = (companyId) => {
  if (!companyId || !COMPANIES[companyId]) {
    console.error(`Invalid company ID: ${companyId}`);
    return "";
  }
  return COMPANIES[companyId].publicApiUrl;
};

export const hasFeature = (companyId, featureName) => {
  if (!companyId || !COMPANIES[companyId]) {
    return false;
  }
  return COMPANIES[companyId].features?.[featureName] || false;
};

export const getCompanyCurrency = (companyId) => {
  if (!companyId || !COMPANIES[companyId]) {
    console.error(`Invalid company ID: ${companyId}`);
    return "$";
  }
  return COMPANIES[companyId].currency;
};

export const getCompanySocketUrl = (companyId) => {
  if (!companyId || !COMPANIES[companyId]) {
    console.error(`Invalid company ID: ${companyId}`);
    return "";
  }
  return COMPANIES[companyId].socketUrl;
};

export const hasTemplate = (companyId, templateId) => {
  if (!companyId || !COMPANIES[companyId]) {
    return false;
  }
  return COMPANIES[companyId].template === templateId;
};
